using UnityEngine;
using System.Collections;


public enum SoundDefinitions
{
	// Musics
	MAIN_THEME					= 0,
	VESTIDOR_THEME				= 1,
	MINIGAME_THEME				= 2,

	// UI CONTROLS
	BUTTON_TICK					= 3,
	BUTTON_FORWARD				= 4,
	BUTTON_BACKWARD				= 5,
	BUTTON_ACCEPT				= 6,

	// MINIGAMES FX
	MINIGAME_FOOTBALL_START		= 7,
	MINIGAME_FOOTBALL_COUNTDOWN	= 8,
	MINIGAME_FOOTBALL_END		= 9,
	HIDEN_OBJECT_FOUND			= 10,
	FOOTBALL_GOAL				= 11,
	BASKET_GOAL					= 12,
	BALL_MISS					= 13,
	MINIGAME_BASKET_START		= 14,
	MINIGAME_BASKET_COUNTDOWN	= 15,
	MINIGAME_BASKET_END			= 16
}